lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import reverse_lazy
from .views import SearchResultsView, AboutPageView

from django.contrib.auth import views as auth_views
from . import views


app_name = 'lesson'


class MyHack(auth_views.PasswordResetView):
    success_url = reverse_lazy("lesson:password_reset_done")


urlpatterns = [
    # path('', views.all_teams, name='all_teams'),
    path('', views.TeamListView.as_view(), name='all_teams'),
    path('<int:yy>/<int:mm>/<int:dd>/<slug:slug>/', 
         views.detailed_team, name = 'detailed_team'),
    path('<int:team_id>/share/', views.share_team,
         name='share_team'),
    path('create/', views.create_team,
         name='create_form'),
#     path('login/', views.custom_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
path('logout/', auth_views.LogoutView.as_view(), name='logout'),

 path("password_reset/", MyHack.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("lesson:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('profile/', views.view_profile, name='profile'),
    path('register/', views.register, name='register'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('about/', AboutPageView.as_view(), name='about'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lesson/', include('lesson.urls', namespace='lesson') )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Team(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique_for_date='publish')

    body = models.TextField()

    cover = models.ImageField(upload_to='images/')

    created  = models.DateField(auto_now_add=True)
    updeted  = models.DateField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_teams')

    publish = models.DateTimeField(default=timezone.now())

    TEAM_TYPE = [
        ('Группа A', 'Группа А в НБЛ'),
        ('Группа B', 'Группа В в НБЛ'),
    ]

    team_type = models.CharField(max_length=25, choices=TEAM_TYPE, default='руппа А')

    # def __str__(self):
    #     return self.title

    def get_absolute_url(self):
        return reverse('lesson:detailed_team',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    team = models.ForeignKey(Team,
                                 on_delete=models.CASCADE,
                                 related_name='comments')
    name = models.CharField(max_length=250)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to="user/%Y/%m/%d/", blank=True)

lesson/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User

class EmailTeamForm(forms.Form):
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class TeamForm(forms.ModelForm):
    class Meta:
        model = models.Team
        fields = ('title', 'body', 'team_type')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'body')


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='password repeat', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("password and password2 aren't equal")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('birth', 'photo')

lesson/views.py
from turtle import title
from django.views.generic import ListView, TemplateView
from django.core.mail import send_mail
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect


from . import models
from . import forms



# Create your views here.


class TeamListView(LoginRequiredMixin, ListView):
    queryset = models.Team.objects.all()
    context_object_name = 'teams'
    template_name = "teams/all_teams.html"
#
# def all_teams(request):
#     teams = models.Team.objects.all()
#     return render(request, "teams/all_teams.html",
#                   {"teams": teams})

@login_required
def detailed_team(request, yy, mm, dd, slug):
    team = get_object_or_404(models.Team, publish__year=yy, 
                                publish__month=mm, publish__day=dd, slug=slug)
    teams = models.Team.objects.all()
    if request.method == "POST":
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.team = team
                new_comment.save()
                return redirect(team)
    else:
        comment_form = forms.CommentForm()

    return render(request, "teams/detailed_team.html",
                  {"team": team,
                   "form": comment_form,
                   "teams": teams})

def share_team(request, team_id):
    team = get_object_or_404(models.Team, id=team_id)
    if request.method == 'POST':
        form = forms.EmailTeamForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            team_uri = request.build_absolute_uri(
                team.get_absolute_url()
            )
            subject = 'Кто-то отправил заявку на участие в спарринге ' + team.title
            body_template = ('На Вашем ресурсе кто-то отправил заявку'
                             '\n\nСсылка на команду {link}\n\nкомментарий: '
                             '{comment}')
            body = body_template.format(link=team_uri,
                                        comment=cd['comment'])
            send_mail(subject, body, 'admin@my.com', (cd['to_email'],))
    else:
        form = forms.EmailTeamForm()
    return render(request,
                  'teams/share.html',
                  {'team':team, 'form': form})


def create_team(request):
    if request.method == 'POST':
        team_form = forms.TeamForm(request.POST)
        if team_form.is_valid():
            new_team = team_form.save(commit=False)
            new_team.author = User.objects.first()
            new_team.slug = new_team.title.replace(' ', '_')
            new_team.save()
            return render(request,
                          "teams/detailed_team.html",
                          {"team": new_team})

    else:
        team_form = forms.TeamForm()
    return render(request,
                  'teams/create.html',
                  {'form': team_form})


def custom_login(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                username=cd['Имя'],
                password=cd['Пароль'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Пользователь вошел в систему')
                else:
                    return HttpResponse('Учетная запись пользователя не активирована')
            else:
                return HttpResponse('Неверное Имя/Пароль')
    else:
        form = forms.LoginForm()
        return render(request, 'login.html', {'form': form})


def view_profile(request):
    return render(request, 'profile.html')


def register(request):
    if request.method == "POST":
        user_form = forms.RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['Пароль'])
            new_user.save()
            models.Profile.objects.create(user=new_user, photo="unknown.jpg")
            return render(request, 'registration/registration_complete.html',
                          {'Новый пользователь': new_user})
        else:
            return HttpResponse('Неверные данные')
    else:
        user_form = forms.RegistrationForm(request.POST)
        return render(request, 'registration/register_user.html', {"form": user_form})


class SearchResultsView(ListView):
    model = models.Team
    template_name = 'teams/search_results.html'

    def get_queryset(self): 
        object_list = models.Team.objects.filter(
            title=self.request.GET.get('q')
            )
        return object_list


def _get_forms(request, post_method):
    user_form = forms.UserEditForm(request.POST, instance=request.user)

    kw = {'instance': request.user.profile}
    if post_method: kw.update({'files': request.FILES})

    profile_form = forms.ProfileEditForm(request.POST, **kw)

    return user_form, profile_form


def edit_profile(request):
    post_method = request.method == "POST"
    user_form, profile_form = _get_forms(request, post_method)

    if post_method:
        if profile_form.is_valid():
            if user_form.is_valid():
                if not profile_form.cleaned_data['Фото']:
                    profile_form.cleaned_data['Фото'] = request.user.profile.photo
                profile_form.save()
                user_form.save()
                return render(request, 'profile.html')
    else:
        return render(request, 'edit_profile.html',
                      {'user_form': user_form, 'profile_form': profile_form})


class AboutPageView(TemplateView):
    template_name = "teams/about.html"

lesson/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <style>
        body {
    background: url(/static/img/basketball.jpg) no-repeat;
    -moz-background-size: cover; /* Firefox 3.6+ */
    -webkit-background-size: cover; /* Safari 3.1+ и Chrome 4.0+ */
    -o-background-size: cover; /* Opera 9.6+ */
    background-size: cover; /* Современные браузеры */
   }
        h4 {
            font-family: sans-serif;
font-size: 14px;
-webkit-print-color-adjust: exact;
        }
        </style>
    <link href="{% static "styles.css" %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %} MY DEFAULT TITLE{% endblock %}</title>
  </head>
  <body>
    <header>
        {% if request.user.is_authenticated %}
            <h4>Здравствуйте, {{ request.user.first_name }}! <a href="{% url "lesson:logout" %}">Выйти</a> <a href="{% url "lesson:profile" %}">Профиль</a></h4>     
        {% else %}
                <a href="{% url "lesson:login" %}">Войти</a>
        {% endif %}
        <br>
    </header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav" style="background-color: papayawhip; font-size: 130%; font-style: inherit; ">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "lesson:all_teams" %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "lesson:about" %}">О сайте</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "lesson:register" %}">Регистрация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "lesson:create_form" %}">Создать новую команду</a>
            </li>
          </ul>
        </div>
      </nav>
    <div class="container-flex m-4">
        <div class="row mb-1">
            <div class="col-3 px-0 pr-1">
             <div class="border border-primary rounded">
                {% block menu %}{% endblock %}
             </div>
            </div>
            <div class="col-9 border border-primary rounded">
                {% block content %}{% endblock %}
            </div>
    
        </div>
        <div class="row border border-primary rounded">
            <div class="col-9">
                Поиск команды для спарринга. Все права защищены.
            </div>
            <div class="col-3">
                Автор: Катерина Селевич
            </div>
        </div>
    
    </div>
   <!-- Option 1: Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

lesson/templates/edit_profile.html
{% extends "base.html" %}

{% block title %}Обновить профиль{% endblock %}

{% block content %}
    <h2>Обновить данные:</h2>
    <form action="." method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Изменить">
    </form>
{% endblock %} 

lesson/templates/login.html
{% extends "base.html" %}

{% block title %}Логин пользователя{% endblock %}

{% block content %}
    <h2>Логин пользователя:</h2>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="login">
    </form>
{% endblock %}

lesson/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
    <h2>Здравствуйте, {{ request.user.first_name }}:</h2>
    <p>Дата рождения: {{ request.user.profile.birth }}</p>
    <a href="{% url "lesson:edit_profile" %}">Изменить профиль:</a>
    <h2>Команды автора:     </h2><br>
    <ul>
        {% for team in request.user.user_teams.all %}
            <li>
                <h3> <a href="{{team.get_absolute_url}}">{{ team.title }}</a></h3>
                Опубликовано: {{ team.publish }}
            </li>
        {% endfor %}
    </ul>

    <p>Аватар: <img src="{{ request.user.profile.photo.url }}" alt="alter text"></p>
{% endblock %}