lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import reverse_lazy
from .views import SearchResultsView, AboutPageView

from django.contrib.auth import views as auth_views
from . import views


app_name = 'lesson'


class MyHack(auth_views.PasswordResetView):
    success_url = reverse_lazy("lesson:password_reset_done")


urlpatterns = [
    # path('', views.all_teams, name='all_teams'),
    path('', views.TeamListView.as_view(), name='all_teams'),
    path('<int:yy>/<int:mm>/<int:dd>/<slug:slug>/', 
         views.detailed_team, name = 'detailed_team'),
    path('<int:team_id>/share/', views.share_team,
         name='share_team'),
    path('create/', views.create_team,
         name='create_form'),
#     path('login/', views.custom_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
path('logout/', auth_views.LogoutView.as_view(), name='logout'),

 path("password_reset/", MyHack.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("lesson:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path('profile/', views.view_profile, name='profile'),
    path('register/', views.register, name='register'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('about/', AboutPageView.as_view(), name='about'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lesson/', include('lesson.urls', namespace='lesson') )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lesson/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Team(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique_for_date='publish')

    body = models.TextField()

    cover = models.ImageField(upload_to='images/')

    created  = models.DateField(auto_now_add=True)
    updeted  = models.DateField(auto_now=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_teams')

    publish = models.DateTimeField(default=timezone.now())

    TEAM_TYPE = [
        ('Группа A', 'Группа А в НБЛ'),
        ('Группа B', 'Группа В в НБЛ'),
    ]

    team_type = models.CharField(max_length=25, choices=TEAM_TYPE, default='руппа А')

    # def __str__(self):
    #     return self.title

    def get_absolute_url(self):
        return reverse('lesson:detailed_team',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    team = models.ForeignKey(Team,
                                 on_delete=models.CASCADE,
                                 related_name='comments')
    name = models.CharField(max_length=250)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth = models.DateTimeField(null=True, blank=True)
    photo = models.ImageField(upload_to="user/%Y/%m/%d/", blank=True)

lesson/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User

class EmailTeamForm(forms.Form):
    to_email = forms.EmailField()
    comment = forms.CharField(required=False,
                              widget=forms.Textarea)


class TeamForm(forms.ModelForm):
    class Meta:
        model = models.Team
        fields = ('title', 'body', 'team_type')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'body')


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='password repeat', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("password and password2 aren't equal")
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('birth', 'photo')

lesson/views.py
from turtle import title
from django.views.generic import ListView, TemplateView
from django.core.mail import send_mail
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect


from . import models
from . import forms



# Create your views here.


class TeamListView(LoginRequiredMixin, ListView):
    queryset = models.Team.objects.all()
    context_object_name = 'teams'
    template_name = "teams/all_teams.html"
#
# def all_teams(request):
#     teams = models.Team.objects.all()
#     return render(request, "teams/all_teams.html",
#                   {"teams": teams})

@login_required
def detailed_team(request, yy, mm, dd, slug):
    team = get_object_or_404(models.Team, publish__year=yy, 
                                publish__month=mm, publish__day=dd, slug=slug)
    teams = models.Team.objects.all()
    if request.method == "POST":
            comment_form = forms.CommentForm(request.POST)
            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                new_comment.team = team
                new_comment.save()
                return redirect(team)
    else:
        comment_form = forms.CommentForm()

    return render(request, "teams/detailed_team.html",
                  {"team": team,
                   "form": comment_form,
                   "teams": teams})

def share_team(request, team_id):
    team = get_object_or_404(models.Team, id=team_id)
    if request.method == 'POST':
        form = forms.EmailTeamForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            team_uri = request.build_absolute_uri(
                team.get_absolute_url()
            )
            subject = 'Кто-то отправил заявку на участие в спарринге ' + team.title
            body_template = ('На Вашем ресурсе кто-то отправил заявку'
                             '\n\nСсылка на команду {link}\n\nкомментарий: '
                             '{comment}')
            body = body_template.format(link=team_uri,
                                        comment=cd['comment'])
            send_mail(subject, body, 'admin@my.com', (cd['to_email'],))
    else:
        form = forms.EmailTeamForm()
    return render(request,
                  'teams/share.html',
                  {'team':team, 'form': form})


def create_team(request):
    if request.method == 'POST':
        team_form = forms.TeamForm(request.POST)
        if team_form.is_valid():
            new_team = team_form.save(commit=False)
            new_team.author = User.objects.first()
            new_team.slug = new_team.title.replace(' ', '_')
            new_team.save()
            return render(request,
                          "teams/detailed_team.html",
                          {"team": new_team})

    else:
        team_form = forms.TeamForm()
    return render(request,
                  'teams/create.html',
                  {'form': team_form})


def custom_login(request):
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                username=cd['Имя'],
                password=cd['Пароль'],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Пользователь вошел в систему')
                else:
                    return HttpResponse('Учетная запись пользователя не активирована')
            else:
                return HttpResponse('Неверное Имя/Пароль')
    else:
        form = forms.LoginForm()
        return render(request, 'login.html', {'form': form})


def view_profile(request):
    return render(request, 'profile.html')


def register(request):
    if request.method == "POST":
        user_form = forms.RegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['Пароль'])
            new_user.save()
            models.Profile.objects.create(user=new_user, photo="unknown.jpg")
            return render(request, 'registration/registration_complete.html',
                          {'Новый пользователь': new_user})
        else:
            return HttpResponse('Неверные данные')
    else:
        user_form = forms.RegistrationForm(request.POST)
        return render(request, 'registration/register_user.html', {"form": user_form})


class SearchResultsView(ListView):
    model = models.Team
    template_name = 'teams/search_results.html'

    def get_queryset(self): 
        object_list = models.Team.objects.filter(
            title=self.request.GET.get('q')
            )
        return object_list


def _get_forms(request, post_method):
    user_form = forms.UserEditForm(request.POST, instance=request.user)

    kw = {'instance': request.user.profile}
    if post_method: kw.update({'files': request.FILES})

    profile_form = forms.ProfileEditForm(request.POST, **kw)

    return user_form, profile_form


def edit_profile(request):
    post_method = request.method == "POST"
    user_form, profile_form = _get_forms(request, post_method)

    if post_method:
        if profile_form.is_valid():
            if user_form.is_valid():
                if not profile_form.cleaned_data['Фото']:
                    profile_form.cleaned_data['Фото'] = request.user.profile.photo
                profile_form.save()
                user_form.save()
                return render(request, 'profile.html')
    else:
        return render(request, 'edit_profile.html',
                      {'user_form': user_form, 'profile_form': profile_form})


class AboutPageView(TemplateView):
    template_name = "teams/about.html"

lesson/templates/teams/about.html
{% extends "base.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
    <h2>О сайте</h2>
    <p>
        Здравствуйте любители баскетбола! Одна из проблем, с которой сталкиваются все кто любит играть в этот вид спорта – поиск спарринг партнеров для игры. Решение этой проблемы найдено! Заполните данные о своей команде ниже в форме или возьмите оттуда чей-либо контакт для игры.

Заполните форму ниже и Ваша команда попадёт в базу.
    </p>
    <a class="nav-link" href="{% url "lesson:create_form" %}">Создать новую команду</a>
{% endblock %}

lesson/templates/teams/all_teams.html
{% extends "base.html" %}
<style>
    h3 {
color: ivory;
}
</style>
{% block menu %}
<h2>Поиск по командам</h2>
    <form action="{% url 'lesson:search_results' %}" method="get"  style="margin: 20px;  border-color: black; border: 5ch; border-radius: 10%;">
        <input name="q" type="text" placeholder="Поиск..."></form>
         
        <table class="table-success" style="width:99%; border: 1px solid black; border-spacing: 0px;   
        margin: 0; color: rgb(0, 13, 77); padding: 0; font-size: medium; ">
            <tr class="table-success">
                <th class="table-success">Команды</td>
                <th class="table-success">Дни тренировок</td>
                </tr>
            <tr class="table-success">
                <td class="table-success">MTS Buzzers</td>
                <td class="table-success">Вторник, четверг</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">Bad boys</td>
                <td class="table-success">Понедельник, пятница</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">Эра-Недвижимости плюс</td>
                <td class="table-success">Понедельник, четверг</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">Eagles</td>
                <td class="table-success">Вторник, четверг</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">SIRIUS</td>
                <td class="table-success">Вторник, пятница</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">БГУФК</td>
                <td class="table-success">Понедельник, среда, пятница</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">DEAF-MINSK</td>
                <td class="table-success">Вторник, четверг</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">Shooters</td>
                <td class="table-success">Вторник, четверг</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">NORD</td>
                <td class="table-success">Среда, суббота</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">TOGI БНТУ</td>
                <td class="table-success">Понедельник, среда, пятница</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">Аматары</td>
                <td class="table-success">Среда, суббота</td>
            </tr>
            <tr class="table-success">
                <td class="table-success">STACKLEVEL</td>
                <td class="table-success">Среда, пятница</td>
            </tr>
        </table>
{% endblock %}

{% block content %}

    <h1>Команды:</h1>
    {% for team in teams %}
    <h3>{{ team.title }}</h3>
        <p>
            {{ team.body|truncatewords:10 }}
        </p>
        <a href="{{team.get_absolute_url}}"> Подробнее о команде </a><br>
    {% endfor %}
{% endblock %}

lesson/templates/teams/create.html
{% extends "base.html" %}

{% block title %}Создать команду{% endblock %}

{% block content %}
    <h2>Создать новую команду:</h2>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Создать команду">
    </form>
{% endblock %}

lesson/templates/teams/detailed_team.html
{% extends "base.html" %}

{% block title %}{{ team.title }}{% endblock %}

{% block content %}
        <a href="{% url "lesson:all_teams" %}">Назад к командам</a>
        <h1>{{ team.title }}</h1>
        <p>{{ team.team_type }}</p>
        <p>{{ team.body|linebreaks }}</p>
        <img src="{{ team.cover.url }}">
        <p>Опубликовано {{ team.publish }} автором {{ team.author }}</p>
        <h3> <a href="{% url "lesson:share_team" team.id %}">Отправить заявку на участие в спарринге</a></h3>
        <p> Оставить комментарий о команде и о зале, в котором проходят тренировки. </p>
    {# comments for team #}
    {% if commented %}
        Вы оставили комментарий
    {% else %}
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" value="Оставить комментарий">
    {% endif %}
    </form>
        <br>
        {% with team.comments.count as total_comments %}
            {{ total_comments }} комментарий{{ total_comments|pluralize }}
        {% endwith %}
<br>
        {% for comment in team.comments.all %}
            <p> Комментарий #{{ forloop.counter }} от пользователя {{ comment.name}}</p>
            {{ comment.body }}
        {% empty %}
            Здесь пока нет комментариев. Вы можете быть первым, кто оставит комментарий.
        {% endfor %}
        
{% endblock %}

lesson/templates/teams/search_results.html
{% load static %}
{% block title %}<h1>Результаты поиска</h1>{% endblock %}
<style>
  .bg{
      width: 100%;
      height: 300px;
      background-image: url("/static/img/sample.jpeg");
  }
  </style>
{% block content %}
 
<ul>
  {% for team in object_list %}
    <li>
      <a href="{{team.get_absolute_url}}"> {{ team.title }} </a>
    </li>
    {% empty %}
    <p>Результатов поиска не обнаружено.</p>
  {% endfor %}
</ul>
<p>
  <a href="{% url "lesson:all_teams" %}"> Попробуйте начать поиск снова </a>
</p>
{% endblock %}

lesson/templates/teams/share.html
{% extends "base.html" %}

{% block title %} Отправить заявку на спарринг {% endblock %}

{% block content %}
    <h2>Укажите свой email:</h2>
    <form action="." method="post">
        {{ form.as_p}}
        {% csrf_token %}
        <input type="submit" value ="Отправить">
    </form>
{% endblock %}